window.DOTS_LEVELS = [
  { id: 1, titleTelugu: "అయోధ్య ద్వారం", titleEnglish: "Ayodhya's Gate",
    pairs: [ { left: "శ్రీరాముడు", right: "కోదండం" }, { labelLeft: "అర్జునుడు", labelRight: "గాండీవం" }, { left: "శ్రీకృష్ణుడు", right: "సుదర్శన చక్రం" } ].map((p,i) => i===1 ? {left:"అర్జునుడు", right:"గాండీవం"} : p) },
  { id: 2, titleTelugu: "పంచవటి వనం", titleEnglish: "Panchavati Grove",
    pairs: [ { left: "శివుడు", right: "పినాకం" }, { left: "విష్ణువు", right: "శార్ంగం" }, { left: "ఇంద్రుడు", right: "వజ్రాయుధం" } ] },
  { id: 3, titleTelugu: "చిత్రకూట ఆశ్రమం", titleEnglish: "Chitrakoot Hermitage",
    pairs: [ { left: "రావణుడు", right: "చంద్రహాసం" }, { left: "కర్ణుడు", right: "వాసవి శక్తి" }, { left: "భీముడు", right: "గద" } ] },
  { id: 4, titleTelugu: "కిష్కింధ సభ", titleEnglish: "Kishkindha Court",
    pairs: [ { left: "పరశురాముడు", right: "పరశువు" }, { left: "కుమారస్వామి", right: "వేల్" }, { left: "యముడు", right: "కాలదండం" } ] },
  { id: 5, titleTelugu: "లంకా ప్రాకారం", titleEnglish: "Lanka's Ramparts",
    pairs: [ { left: "సీతాదేవి", right: "అశోకవనం" }, { left: "లక్ష్మణుడు", right: "ఊర్మిళ" }, { left: "భgeneric", right: "మాండవి" } ].map((p,i) => i===2 ? {left:"భరతుడు", right:"మాండవి"} : p) },
  { id: 6, titleTelugu: "అశోక వనం", titleEnglish: "Ashoka Vatika",
    pairs: [ { left: "దశరథుడు", right: "అయోధ్య" }, { left: "జనకుడు", right: "మిథిల" }, { left: "సుగ్రీవుడు", right: "కిష్కింధ" } ] },
  { id: 7, titleTelugu: "శబరి కుటీరం", titleEnglish: "Sabari's Cottage",
    pairs: [ { left: "హనుమంతుడు", right: "అంజనాదేవి" }, { left: "అభిమన్యుడు", right: "సుభద్ర" }, { left: "ఘటోత్కచుడు", right: "హిడింబ" } ] },
  { id: 8, titleTelugu: "ఋశ్యమూక పర్వతం", titleEnglish: "Rishyamuka Hill",
    pairs: [ { left: "వాలి", right: "తార" }, { left: "హరిశ్చంద్రుడు", right: "చంద్రమతి" }, { left: "నలుడు", right: "దమయంతి" } ] },
  { id: 9, titleTelugu: "దండకారణ్యం", titleEnglish: "Dandaka Forest",
    pairs: [ { left: "వశిష్ఠుడు", right: "అరుంధతి" }, { left: "అగస్త్యుడు", right: "లోపాముద్ర" }, { left: "గౌతముడు", right: "అహల్య" } ] },
  { id: 10, titleTelugu: "మిథిలా నగరం", titleEnglish: "Mithila Kingdom",
    pairs: [ { left: "లక్ష్మి", right: "పద్మము" }, { left: "సరస్వతి", right: "వీణ" }, { left: "పార్వతి", right: "త్రిశూలం" } ] },
  { id: 11, titleTelugu: "క్షీర సాగరం", titleEnglish: "Cosmic Ocean",
    pairs: [ { left: "వినాయకుడు", right: "మూషికం" }, { left: "కుమారస్వామి", right: "నెమలి" }, { left: "శివుడు", right: "నంది" } ] },
  { id: 12, titleTelugu: "శ్రీరామ సామ్రాజ్యం", titleEnglish: "Rama's Empire",
    pairs: [ { left: "లవుడు", right: "కుశుడు" }, { left: "ఉపపాండవులు", right: "ఐదుగురు" }, { left: "నవగ్రహాలు", right: "తొమ్మిది" } ] }
];
